export const user = {
    user: "Erica Clapton",
    email: "erica.clapton@gmail.com",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg"
};

export const messages = [
    {
        id: 0,
        from: 'Marta Lichardson',
        email: 'marta.lichardson@gmail.com',
        subject: `Design new project "Anama"`,
        message: 'How long will it take you to transfer all the data to us ?',
        time: '2020-10-14T12:59-0000',
        cat: 'family',
        starred: false,
        new: false,
        attachments: [],
        avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
        replies: [],
    },
    {
        id: 1,
        from: 'Derek Lichardson',
        email: 'derek.lichardson@gmail.com',
        subject: 'Design template',
        message: `Good afternoon, We've all received those flashy marketing emails... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum`,
        time: '2020-10-12T11:59-0000',
        cat: 'work',
        starred: true,
        new: false,
        attachments: ['Template.psd', 'Description.doc'],
        avatar: 'https://randomuser.me/api/portraits/men/97.jpg',
        replies: [
            {
                id: 7,
                from: user.name,
                email: user.email,
                subject: 'Design template',
                message: 'Hi, I will send you the full length...',
                time: '2020-10-14T12:59-0000',
                cat: 'family',
                starred: false,
                new: false,
                attachments: [],
                avatar: user.avatar,
                replies: [],
            },
        ],
    },
    {
        id: 2,
        from: 'Bogdan Tuman',
        email: 'bogdan.tuman@gmail.com',
        subject: `Design new project "Anama"`,
        message: 'Hello everyone, where can I find new mockups for design...?',
        time: '2020-04-19T12:59-0500',
        cat: 'client',
        starred: false,
        new: true,
        attachments: [],
        avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
        replies: [],
    },
    {
        id: 3,
        from: 'Bogdan Tuman',
        email: 'bogdan.tuman@gmail.com',
        subject: `Design new project "Anama"`,
        message: 'Hello everyone, where can I find new mockups for design...?',
        time: '2020-10-11T12:59-0500',
        cat: 'friends',
        starred: false,
        new: true,
        attachments: [],
        avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
        replies: [],
    },
    {
        id: 4,
        from: 'Amarinda Faram',
        email: 'amarinda.faram@gmail.com',
        subject: `Design new project "Anama"`,
        message: 'Hello everyone, where can I find new mockups for design...?',
        time: '2020-10-12T12:59-0500',
        cat: 'work',
        starred: false,
        new: true,
        attachments: [],
        avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
        replies: [],
    },
    {
        id: 5,
        from: 'Bogdan Tuman',
        email: 'bogdan.tuman@gmail.com',
        subject: `Design new project "Anama"`,
        message: 'Hello everyone, where can I find new mockups for design...?',
        time: '2020-04-19T12:59-0500',
        cat: 'work',
        starred: false,
        new: true,
        attachments: [],
        avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
        replies: [],
    },
    {
        id: 6,
        from: 'Bogdan Tuman',
        email: 'bogdan.tuman@gmail.com',
        subject: `Design new project "Anama"`,
        message: 'Hello everyone, where can I find new mockups for design...?',
        time: '2020-04-19T12:59-0500',
        cat: 'work',
        starred: false,
        new: true,
        attachments: [],
        avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
        replies: [],
    },
]